FROM alpine:3.18

RUN apk add --no-cache nginx curl iputils-ping tcpdump bind-tools

COPY default.conf /etc/nginx/http.d/default.conf
COPY index.html /usr/share/nginx/html/index.html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
