FROM python:latest

RUN apt-get update
RUN apt-get install -y vim git curl
RUN pip install flask==2.0.1
RUN pip install gunicorn==20.1.0
RUN pip install requests==2.26.0

WORKDIR /app

COPY . /app/

ENV SECRET_KEY="development_key_123456"
ENV DEBUG=True

EXPOSE 5000

CMD ["python", "app.py"]
